### ISSUE TITLE
WhiteboxTools for Processing 1.0.0

### ISSUE THREAD

**Issue by pedrodrigues2020** [alexbruy/processing-wbt#33]
I had try to put "WhiteboxTools for Processing 1.0.0" qgis plugin on QGIS 3.10 long term realese and don´t apear on plugins list to install then i can't use whitebox tools on QGIS 3.10 long term realese, i think the last version (1.0.0) of this plugin only works on Qgis 3.12. 

Is it possible to obtain one version work on QGIS 3.10 long term realese?

**Comment by alexbruy** [comment]
Version 1.0 needs QGIS >= 3.12 as it relies on the latest changes in the QGIS API. Use older version of the plugin if you are using old QGIS versions.

And please, don't submit multiple duplicate tickets.

**Comment by pedrodrigues2020** [comment]
thanks
where i could obtain a older version to use on Qgis 3.10 long term?

**Comment by jasonfischer** [comment]
I'm having a similar issue, with the WhiteboxTools for Processing plugin not appearing in the plugins list, even though I have linked to your repository. I don't have installation privileges on my computer, so adding an earlier version of the plugin is preferred to installing QGIS 3.12. Is an earlier version of the plugin still available for the QGIS 3.10 long term release?
