### ISSUE TITLE
Could not find watershed tool from whitebox-tools QGIS plugin

### ISSUE THREAD

**Issue by yhan27** [alexbruy/processing-wbt#34]
I installed the latest WBT QGIS plugin (https://plugins.bruy.me/plugins/plugins.xml#whitebox) and WBT itself. Everything is working fine but I could not find the watershed tool. 

I posted this question on the WBT Github page, and the answer from the author is copied below: 

> This is an issue for the QGIS Whitebox front-end, not the WBT backend. The watershed tool is listed in the backend and is accessible from the Whitebox Runner application (and the Python API). I am closing this issue now but feel free to raise the issue with Alex, who maintains the Q front end.

**Comment by alexbruy** [comment]
![image](https://user-images.githubusercontent.com/776954/83221211-d84b0300-a17d-11ea-9a72-81ca9cb99ace.png)
