### ISSUE TITLE
watershed tool missing

### ISSUE THREAD

**Issue by johnpony** [alexbruy/processing-wbt#35]
"I installed the latest WBT QGIS plugin (https://plugins.bruy.me/plugins/plugins.xml#whitebox) and WBT itself. Everything is working fine but I could not find the watershed tool. Any thought?"

This isssue was raised here, https://github.com/jblindsay/whitebox-tools/issues/92#issue-626741920

I have the same issue.

Hope you can help,

Kind regards
John

**Comment by alexbruy** [comment]
Duplicates #34.
