### ISSUE TITLE
installation of plugin not working: https://plugins.bruy.me/plugins/plugins.xml

### ISSUE THREAD

**Issue by kristenbill** [alexbruy/processing-wbt#36]
Hi, 
I'm currently trying to install the plugin:  https://plugins.bruy.me/plugins/plugins.xml so that I can use Whitebox tools. However, it looks like I keep getting the same error message: Error reading repository; unknown. I am currently following these instructions https://jblindsay.github.io/wbt_book/qgis_plugin.html. 

Thanks, 
Kristen

**Comment by alexbruy** [comment]
Just tested and for me everything works fine. Looks like a local issue.

Make sure that you use correct URL and proxy settings (if any). Also checking network requests with some tool may help to understand what's wrong.
