### ISSUE TITLE
QGIS Plugin installation error

### ISSUE THREAD

**Issue by jpmill09** [alexbruy/processing-wbt#38]
QGIS : 3.10 LTR

When attempting to install plugin using directions from [Whiteboxtools User Manual](https://jblindsay.github.io/wbt_book/qgis_plugin.html#installation-of-the-plugin) an error message occurs after completing step 3. 

1. From the **Plugins** menu, select **Manage and Install Plugins**....
2. Select the **Settings** tab and press the **Add** button.
3. In the **Repository details** dialog box, enter `https://plugins.bruy.me/plugins/plugins.xml` in the **Name** textbox and press **OK**.

Error message states:

"Error reading repository: https:
Protocol "" is unknown

![Whiteboxtools Plugin Error](https://user-images.githubusercontent.com/35961262/98004280-bb1a0080-1dbd-11eb-8b34-4db0c737e774.png)

**Comment by alexbruy** [comment]
Please refer to QGIS User Guide on how to work with plugins.
