### ISSUE TITLE
Problems with the repository for QGIS plugin install

### ISSUE THREAD

**Issue by dportillap** [alexbruy/processing-wbt#40]
I have tried to install some of the QGIS plugins in the alexbruy repository https://plugins.bruy.me/plugins/plugins.xml, but for each plugin get the following message:

Plugin installation failed: Error transferring https://plugins.bruy.me/plugins/processing_wbt.zip - server replied: Not Found

I want to install the White box Tools for Processing plugin following the user manual at: https://jblindsay.github.io/wbt_book/qgis_plugin.html, but I can't make it work (QGIS 3.16 and 3.18)

**Comment by Chieffred23** [comment]
The exact same error is happening to me, can't get it to work either.

**Comment by vtetreault** [comment]
I have the same issues with QGIS 3.16.5

**Comment by wZhGIS** [comment]
The same 3.18.1

**Comment by cvdwilde** [comment]
Having the same issue

**Comment by jpknightly** [comment]
I've had the same issue on both Linux and Windows. Last week (Thursday) I was unable to install the plugin on a version of QGIS installed on my Linux OS. Thought it was a version issue with QGIS so I tried a fresh install on Windows 3.18 today and have the same issue. Copied the link (https://plugins.bruy.me/plugins/processing_wbt.zip) into my browser and it appears to be broken.

**Comment by ClemNWRPC** [comment]
Having this issue as well, in QGIS 3.16.6.

**Comment by pbessin** [comment]
Dear Alexander Bruy,

Like previous collegues, I have tried to install your QGIS plugins located at https://plugins.bruy.me/plugins/plugins.xml, and the QGIS Plugin Manager sends the same error message : 'Error transferring https://plugins.bruy.me/plugins/processing_wbt.zip - server replied: Not Found'

I tried to install the plugin from the .zip of your Github repository but it is for QGIS 2.99 so it does not work on my QGIS 3.16.2

Thanks for your time about this issue, I am looking forward to using Whitebox that seems great !

Best Regards,

P. Bessin

**Comment by bellanz80** [comment]
I confirm, on POP_OS 20.10, QGIS 3.18.2

**Comment by mfvescovi** [comment]
Hi!

FTR, I was looking at the code on GitHub and realized that it's not
synced with packages provided on repository; in fact, on
`metadata.txt` I read:

``` text
version=0.1.0
qgisMinimumVersion=2.99
```

where the repository states that current version is 1.2.0 and the
minimum version for QGIS is 3.12.0 ... weird!
Updating those fields and compiling the package brings to a working plugin.

Hope this helps, somehow!

**Comment by bellanz80** [comment]
> Hi!
> 
> FTR, I was looking at the code on GitHub and realized that it's not
> synced with packages provided on repository; in fact, on
> `metadata.txt` I read:
> 
> ```
> version=0.1.0
> qgisMinimumVersion=2.99
> ```
> 
> where the repository states that current version is 1.2.0 and the
> minimum version for QGIS is 3.12.0 ... weird!
> Updating those fields and compiling the package brings to a working plugin.
> 
> Hope this helps, somehow!

Very thank`s!

**Comment by alexbruy** [comment]
Please don't post harmful instructions.

**Comment by mfvescovi** [comment]
Hi!

Il dom 25 apr 2021, 12:01 Alexander Bruy ***@***.***> ha
scritto:

> Please don't post harmful instructions.
>
Fix your repository, then.

>

**Comment by alexbruy** [comment]
> Fix your repository, then.

Please, choose your words. You are not the person who can give orders. I am not paid for anything by you or anyone else. Everything I do is done on a volunteer basis and in my (limited) spare time.

Such comments as yours does not help at all, moreover they are discouraging.

**Comment by mfvescovi** [comment]
Il dom 25 apr 2021, 12:45 Alexander Bruy ***@***.***> ha
scritto:

> Fix your repository, then.
>
> Please, choose your words. You are not the person who can give orders. I
> am not paid for anything by you or anyone else. Everything I do is done on
> a volunteer basis and in my (limited) spare time.
>
It's more than 10 years that I'm volunteering in the Debian Project,
spending all my spare time on it. I can assure you that I know what it's
all about.

> Such comments as yours does not help at all, moreover they are
> discouraging.
>
You removed my innocent comment pointing out where to search for the
culprit for a possible fail... such behaviour is discouraging, in my
opinion.
Anyway, sorry for offending your hard work on wbt-processing.

Cheers.

**Comment by wonder-sk** [comment]
Hi @alexbruy!

Some friends were asking me about availability of the plugin - it seems that the URL in your plugin repository is indeed giving 404 not found error. Is there any chance to get that fixed?

Cheers
Martin

**Comment by alexbruy** [comment]
Hi @wonder-sk!
I'm a bit out of time these days, but plan to fix it in the coming days.

**Comment by wonder-sk** [comment]
Awesome, thanks a lot Alex!
