### ISSUE TITLE
Whitebox provider options not showing up

### ISSUE THREAD

**Issue by leszekmp** [alexbruy/processing-wbt#46]
Installed the WhiteBox Tools plugin in QGIS 3.20.2. Went to Options => Processing => Providers, and clicked the down arrow next to WhiteBox tools. The only line item that shows up is Whitebox Tools executable, and there's no way to enter the executable location there. There are also no check boxes for Activate or Log commands. Tried quitting the program and restarting, didn't fix the problem. Reinstalled the plugin, still no go. Checkboxes and file/folder options work for the other plugins I have installed.

**Comment by alexbruy** [comment]
I don't see what is wrong here. The title says "options not showing up" while the description says options are there.

As for executable location — it works fine for me.

**Comment by leszekmp** [comment]
Thanks for responding, but I think you may have misread my original comment; nowhere in the comment do I say that the options are there for Whitebox Tools. It says that the "Checkboxes and file/folder options work for the other plugins I have installed", i.e. all of them except for Whitebox Tools. For Whitebox Tools, "The only line item that shows up is Whitebox Tools executable, and there's no way to enter the executable location there", and "There are also no check boxes for Activate or Log commands". I have attached a screenshot of the Providers section showing this. 

![QGIS_providers](https://user-images.githubusercontent.com/8127516/130268466-6efe8e9a-cca8-4899-918d-0b656784bd70.png)

**Comment by alexbruy** [comment]
The title says `Whitebox provider options not showing up` while in the description I see `The only line item that shows up is Whitebox Tools executable` which is completely opposite to what the title says. What is more, issue description means that all options are there. So there is nothing wrong and this is not a valid issue. Hence it was closed.

**Comment by leszekmp** [comment]
My apologies - I assumed there would be a box for "Activation" in the Provider settings. I still had the inability to specify the whitebox_tools executable, but I solved that by uninstalling then reinstalling Whitebox Tools
