### ISSUE TITLE
QGIS crashes after running model - Yield Filter

### ISSUE THREAD

**Issue by Eirma09** [alexbruy/processing-wbt#47]
Hi!

All the tools I have tried in the plugin works well. However, it crashes when the Yield Filter tool is ran in a model (either in Model Designer or Processing Toolbox. 

It still produces the output but the QGIS project crashes/closes without giving any errors.

Any help would be appreciated.
Thank you!

**Comment by Eirma09** [comment]
> You need a license for the [General Toolset Extension](https://www.whiteboxgeo.com/whitebox-general-toolset/) or the [Agriculture Extension](https://www.whiteboxgeo.com/whitebox-agriculture-extension/) to run this tool.

Yep, I do have one.

**Comment by alexbruy** [comment]
It was an upstream issue, fixed installers are already available. You need to download installer again, uninstall existing copy and then reinstall QGIS using new installer.
