### ISSUE TITLE
Can't install plugin - instructions?

### ISSUE THREAD

**Issue by goney3** [alexbruy/processing-wbt#48]
I downloaded the zip of this project and then tried to install from the zip file in QGIS, this gave me several errors. Are there any installation instructions for getting this plugin installed in QGIS? I couldn't find it in the QGIS plugin list either, I am using v3.20.3

**Comment by alexbruy** [comment]
Source code hosted on GitHub is for developers and power users. You should install plugin from the plugin repository instead. If you are not familiar with plugin management in QGIS there is a detailed section about it in the QGIS user guide.

**Comment by goney3** [comment]
Alex, it's not in the plugin repository, not in QGIS or on your website. Is it not compatible with v3.20.3? The 3.20 versions are very different than prior versions. Please check instead of stating the obvious. Thank you.

**Comment by alexbruy** [comment]
> Alex, it's not in the plugin repository, not in QGIS or on your website.

![plunig](https://user-images.githubusercontent.com/776954/139563808-6be41583-187e-4b2c-8fdf-a0ce55442af0.png)

> The 3.20 versions are very different than prior versions

As QGIS core developer I know that that's not true at all. The API, including Processing one remains the same, there are no breaking changes. Also in the repository it is clearly stated that there is a minimum QGIS version requirement (3.18 at the moment) and no maximum QGIS version requirement is set.

> Please check instead of stating the obvious.

I am afraid can say almost the same. Please, read QGIS documentation about plugins management and information at the plugin page. These two sources contain all necessary information.

**Comment by goney3** [comment]
Well, thank you for the screenshot. I'll make sure to include my own when I get back to the office on Monday. Unless it's somehow blocked behind the municipal firewall it's simply not there my friend.

**Comment by alexbruy** [comment]
I can't help with the firewall, sorry. But the repository works fine and I can access it from Windows and Linux machines using any supported QGIS version (this means any version from 3.18.0).

**Comment by goney3** [comment]
Again, other plugins aren't an issue. Only this one for some reason.

I really hope you can add your screenshot above to your plugins page that links from Whitebox, documentation and communication are always great to address as a developer. Currently the way it's setup its going in a loop with no obvious "download", especially if it does not appear in the QGIS repository. Which leaves users to either move on to something else, or to ask a question here (and there doesn't seem to be much activity, so maybe that speaks for itself).
