### ISSUE TITLE
Can't select a .laz file when using LazToLas 

### ISSUE THREAD

**Issue by mpickering** [alexbruy/processing-wbt#49]
The LazToLas tool doesn't allow you to select a .laz file as the dialog only shows .las files. This makes the tool unusable.

In another note, I believe all the tools now accept both .laz and .las files from whitebox-tools-2.0

**Comment by alexbruy** [comment]
This is not a bug, but known limitation of the Processing. It will be resolved with the release of QGIS 3.24 where necessary changes were made.
